#pragma once

class CPed
{
public:
	* AddGogglesModel(int, bool*)
	* AddWeaponModel(int)
	* AttachPedToBike(CEntity*, CVector, unsigned short, float, float, eWeaponType)
	* AttachPedToEntity(CEntity*, CVector, unsigned short, float, eWeaponType)
	* CPed(unsigned int)
	* CalculateNewOrientation()
	* CalculateNewVelocity()
	* CanBeArrested()
	* CanBeDeleted()
	* CanBeDeletedEvenInVehicle()
	* CanPedHoldConversation()
	* CanSeeEntity(CEntity*, float)
	* CanSetPedState()
	* CanStrafeOrMouseControl()
	* CanThrowEntityThatThisPedIsHolding()
	* CanUseTorsoWhenLooking()
	* CanWeRunAndFireWithWeapon()
	* ClearAimFlag()
	* ClearAll()
	* ClearLook()
	* ClearLookFlag()
	* ClearWeapon(eWeaponType)
	* ClearWeapons()
	* CreateDeadPedMoney()
	* CreateDeadPedPickupCoors(float*, float*, float*)
	* CreateDeadPedWeaponPickups()
	* DeadPedMakesTyresBloody()
	* DeleteRwObject()
	* DettachPedFromEntity()
	* DisablePedSpeech(short)
	* DisablePedSpeechForScriptSpeech(short)
	* DoFootLanded(bool, unsigned char)
	* DoGunFlash(int, bool)
	* DoWeHaveWeaponAvailable(eWeaponType)
	* DoesLOSBulletHitPed(CColPoint&)
	* Dress()
	* DropEntityThatThisPedIsHolding(unsigned char)
	* EnablePedSpeech()
	* EnablePedSpeechForScriptSpeech()
	* FinishJumpCB(CAnimBlendAssociation*, void*)
	* FlagToDestroyWhenNextProcessed()
	* GetBikeRidingSkill()
	* GetBonePosition(RwV3d&, unsigned int, bool)
	* GetEntityThatThisPedIsHolding()
	* GetHeadAndFootPositions(CVector&, CVector&, bool)
	* GetHoldingTask()
	* GetLocalDirection(CVector2D const&)
	* GetPedStateString()
	* GetPedTalking()
	* GetTransformedBonePosition(RwV3d&, unsigned int, bool)
	* GetWalkAnimSpeed()
	* GetWeaponSkill()
	* GetWeaponSkill(eWeaponType)
	* GetWeaponSlot(eWeaponType)
	* GiveDelayedWeapon(eWeaponType, unsigned int)
	* GiveObjectToPedToHold(int, unsigned char)
	* GiveWeapon(eWeaponType, unsigned int, bool)
	* GiveWeaponAtStartOfFight()
	* GiveWeaponWhenJoiningGang()
	* GrantAmmo(eWeaponType, unsigned int)
	void Initialise();
	* IsAlive() const
	* IsPedHeadAbovePos(float)
	* IsPedInControl()
	* IsPedShootable()
	* IsPlayer() const
	* IsPlayingHandSignal()
	* IsPointerValid()
	* KillPedWithCar(CVehicle*, float, bool)
	* Load()
	* Look()
	* MakeTyresMuddySectorList(CPtrList&)
	* OurPedCanSeeThisEntity(CEntity*, bool)
	* PedCanPickUpPickUp()
	* PedIsInvolvedInConversation()
	* PedIsReadyForConversation(bool)
	* PlayFootSteps()
	* PositionAnyPedOutOfCollision()
	* PositionAttachedPed()
	* PositionPedOutOfCollision(int, CVehicle*, bool)
	* PreRender()
	* PreRenderAfterTest()
	* ProcessBuoyancy()
	* ProcessControl()
	* ProcessEntityCollision(CEntity*, CColPoint*)
	* PutOnGoggles()
	* ReleaseCoverPoint()
	* RemoveBodyPart(int, signed char)
	* RemoveGogglesModel()
	* RemoveLighting(bool)
	* RemoveWeaponAnims(int, float)
	* RemoveWeaponForScriptedCutscene()
	* RemoveWeaponModel(int)
	* RemoveWeaponWhenEnteringVehicle(int)
	* Render()
	* ReplaceWeaponForScriptedCutscene()
	* ReplaceWeaponWhenExitingVehicle()
	* RequestDelayedWeapon()
	* ResetGunFlashAlpha()
	* RestartNonPartialAnims()
	* RestoreHeadingRate()
	* RestoreHeadingRateCB(CAnimBlendAssociation*, void*)
	* Save()
	* Say(unsigned short, unsigned int, float, unsigned char, unsigned char, unsigned char)
	* SayScript(int, unsigned char, unsigned char, unsigned char)
	* SetAimFlag(CEntity*)
	* SetAimFlag(float)
	* SetAmmo(eWeaponType, unsigned int)
	* SetCharCreatedBy(unsigned char)
	* SetCurrentWeapon(eWeaponType)
	* SetCurrentWeapon(int)
	* SetGunFlashAlpha(bool)
	* SetIdle()
	* SetLook(CEntity*)
	* SetLook(float)
	* SetLookFlag(CEntity*, bool, bool)
	* SetLookFlag(float, bool, bool)
	* SetLookTimer(unsigned int)
	* SetModelIndex(unsigned int)
	* SetMoveAnim()
	* SetMoveAnimSpeed(CAnimBlendAssociation*)
	void SetMoveState(eMoveState moveState);
	* SetPedDefaultDecisionMaker()
	* SetPedPositionInCar()
	* SetPedState(ePedState)
	* SetPedStats(ePedStats)
	* SetRadioStation()
	* SetWeaponLockOnTarget(CEntity*)
	* SetWeaponSkill(eWeaponType, signed char)
	* SetupLighting()
	* ShoulderBoneRotation(RpClump*)
	* SortPeds(CPed**, int, int)
	* SpawnFlyingComponent(int, signed char)
	* SpecialEntityCalcCollisionSteps(bool&, bool&)
	* SpecialEntityPreCollisionStuff(CPhysical*, bool, bool&, bool&, bool&, bool&)
	* StopNonPartialAnims()
	* StopPlayingHandSignal()
	* TakeOffGoggles()
	* Teleport(CVector, unsigned char)
	* TurnBody()
	* Undress(char*)
	* Update()
	* UpdatePosition()
	* UpdateStatEnteringVehicle()
	* UpdateStatLeavingVehicle()
	* UseGroundColModel()
	* WorkOutHeadingForMovingFirstPerson(float)
	* operator delete(void*)
	* operator delete(void*, int)
	* operator new(unsigned int)
	* operator new(unsigned int, int)
	* ~CPed()
protected:
private:
    	* m_sGunFlashBlendOutRate
	* m_sGunFlashBlendStart
	* nCloseBlockedLosWaitTime
	* nFarBlockedLosWaitTime

};